### ISSUE TITLE
Epic: Decentralized Orderbook

### ISSUE THREAD

**Issue by yosriady** [comit-network/ambrosia#3]
**Pitch**
https://3.basecamp.com/4403044/buckets/16930224/messages/2632331598

<img width="658" alt="Screenshot 2020-05-12 at 6 12 52 PM" src="https://user-images.githubusercontent.com/1084226/81672080-37b9cb00-947c-11ea-9400-f9580f2591ed.png">

**TODOs**

- [x] Refund Redeem flow https://github.com/comit-network/app/issues/18
  - Show manual buttons
  - Display Refund button if possible
  - **Implement a canRefund() function in the state machine.**
- [x] Dashboard screen
  - **Important**: Do a Text UI for the home screen, that says 'I want to ____ ____' e.g. 'I want to buy BTC with DAI', where inputs are dropdowns
  - The idea is that in the long run we can extend this screen to allow to filter for various trading pairs.  
- [x] Orderbook screen(s)
  - Lists Orders (Order: trading pair, amounts, expiry, makerPeerId, rate)
     - An overview of available orders to take. [e](https://beta.bounty0x.io/bounties) [g](https://gitcoin.co/hackathon/longhash?tab=hackathon:22)
  - View Order - a modal with a Take button to proceed with the swap
     - After an order was taken, transitions to the swap progress screen
  - [x] Flesh out list element component
     - make currency and amount a single horizontal line
     - make list item element thinner, like a ticker line
     - make entire list item element clickable, opening modal
  - [x] Simplify filters
     - Change dropdowns to radio buttons [BTC->DAI DAI->BTC All]
- [ ] ~~Unmount / migrate away from Electron~~ https://github.com/comit-network/app/issues/45
- [x] Port hooks /providers e.g. `useEthereumWallet` to use `settings` store instead of env vars
- [x] Add providers to `App.tsx`
  - [x] EthereumWallet
  - [x] BitcoinWallet
  - [ ] ~~Cnd~~
  - [ ] ~~ComitClient?~~
- [x] Review orderbook REST API
  - https://github.com/comit-network/comit-rs/blob/dbook2/api_tests/tests/orderbook.ts
- [x] Implement Orderbook module / Integrate with REST API https://3.basecamp.com/4403044/buckets/16930224/messages/2632331598#__recording_2648784219
  - [x] getOrders()
      - https://swr.now.sh/
  - [x] fillOrder()
  - [ ] Integrate Orderbook module functions with actual orderbook UI
      - The goal is to just display orders and take orders, converting it to a swap
      - [ ] Exchange page should pull real data from Orderbook.getOrders()
      - [ ] Order confirmation page should call Orderbook.fillOrder()
  - [x] Set up postman collection to create the Maker's orders for demo purposes
- [ ] Upgrade to latest SDK https://github.com/comit-network/taker-ui/issues/4
   - [x] Port Wallet balances component https://github.com/comit-network/app/blob/master/app/containers/WalletBalances.tsx
   - [ ] display ETH wallet balance (first)
   - [ ] display bitcoin wallet balance
         - new bitcoind wallet requires username and password https://github.com/comit-network/create-comit-app/blob/c7f5bae242a4d8d7e2b9081d84a9a8a2fecf6a4e/scripts/src/docker/bitcoin.rs#L23-L24
   - [ ] ~~call cnd.getSwaps() ~~
- [x] Link new Orderbook pages to Swap page controllers
- [x] Swap detail pages
  - get swap by id https://github.com/comit-network/app/blob/master/app/containers/SwapDetailsPage.tsx#L23
- [ ] Swap Progress UI https://github.com/comit-network/app/issues/21
  - Should add tx [links](https://rimble.consensys.design/templates/tx-summary) to transactions
